// Generates src/glyphs.ts from the original signature-animation source.
// Usage: node scripts/generate-glyphs.mjs [pathToSourceRepo]
// Defaults to cloning the upstream repo into /tmp.
import { readFileSync, writeFileSync } from 'node:fs'
import { execSync } from 'node:child_process'
import { existsSync } from 'node:fs'

let SRC = process.argv[2]
if (!SRC) {
  SRC = '/tmp/signature-animation-src'
  if (!existsSync(SRC)) {
    execSync(
      `git clone --depth 1 https://github.com/Ayo-Osota/signature-animation.git ${SRC}`,
      { stdio: 'inherit' },
    )
  }
}

const lettersSrc = readFileSync(`${SRC}/src/utils/letters.ts`, 'utf8')
const css = readFileSync(`${SRC}/src/App.css`, 'utf8')

const data = {}

// 1. path "d" + width from each glyph's inline SVG string
const glyphRe = /^\s+([A-Za-z]):\s*`([\s\S]*?)`,?\s*$/gm
let m
while ((m = glyphRe.exec(lettersSrc))) {
  const key = m[1]
  const svg = m[2]
  const d = (svg.match(/d="([^"]+)"/) || [])[1]
  const width = parseInt((svg.match(/width="(\d+)"/) || [])[1], 10)
  if (d && Number.isFinite(width)) data[key] = { d, width }
}

// 2. fallback dash length: ".up.a path { stroke-dasharray: 190 }"
const lenRe = /\.(up|lo)\.([a-z])\s+path\s*\{\s*stroke-dasharray:\s*([\d.]+)/g
while ((m = lenRe.exec(css))) {
  const key = m[1] === 'up' ? m[2].toUpperCase() : m[2]
  if (data[key]) data[key].len = parseFloat(m[3])
}

// 3. kerning margins: ".up.a { margin: 0 -10px 0 -7px }" (supports grouped
//    selectors and bare "0" values)
const marRe =
  /((?:\.(?:up|lo)\.[a-z]\s*,?\s*)+)\{[^}]*?margin:\s*0\s+(-?[\d.]+px|0)\s+0\s+(-?[\d.]+px|0)/g
while ((m = marRe.exec(css))) {
  const sels = m[1].match(/\.(up|lo)\.([a-z])/g) || []
  const mr = parseFloat(m[2])
  const ml = parseFloat(m[3])
  for (const s of sels) {
    const mm = s.match(/\.(up|lo)\.([a-z])/)
    const key = mm[1] === 'up' ? mm[2].toUpperCase() : mm[2]
    if (data[key]) {
      data[key].ml = ml
      data[key].mr = mr
    }
  }
}

// 4. validate completeness
const keys = Object.keys(data).sort()
const incomplete = keys.filter(
  (k) =>
    data[k].d == null ||
    data[k].width == null ||
    data[k].len == null ||
    data[k].ml == null ||
    data[k].mr == null,
)
if (keys.length !== 52 || incomplete.length) {
  throw new Error(
    `glyph generation incomplete: ${keys.length} keys, missing fields on [${incomplete}]`,
  )
}

// 5. emit src/glyphs.ts
let out = '// AUTO-GENERATED by scripts/generate-glyphs.mjs — do not edit by hand.\n'
out += 'export interface Glyph {\n'
out += '  /** path "d" attribute */\n  d: string\n'
out += '  /** svg width; viewBox is "0 0 width 51" */\n  width: number\n'
out += '  /** original CSS dash length; fallback when getTotalLength() is unavailable */\n  len: number\n'
out += '  /** kerning margin-left in px (may be negative) */\n  ml: number\n'
out += '  /** kerning margin-right in px (may be negative) */\n  mr: number\n'
out += '}\n\n'
out += 'export const GLYPH_HEIGHT = 51\n\n'
out += 'export const glyphs: Record<string, Glyph> = {\n'
for (const k of keys) {
  const g = data[k]
  out += `  ${JSON.stringify(k)}: { d: ${JSON.stringify(g.d)}, width: ${g.width}, len: ${g.len}, ml: ${g.ml}, mr: ${g.mr} },\n`
}
out += '}\n'

writeFileSync(new URL('../src/glyphs.ts', import.meta.url), out)
console.log(`wrote src/glyphs.ts with ${keys.length} glyphs`)
